import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import Vue from 'vue'


import { faPhone, faBuilding, faRotate, faHouseChimney, faTruckMoving, faSuitcase, faUsers, faGlobe, faLink, faMagnifyingGlass, faGear, faLightbulb, faEnvelope, faClock, faArrowRight, faArrowUpRightDots, faPeopleGroup, faChartPie, faSquarePlus, faSquarePollVertical, faRectangleList, faAngleDown, faTrophy, faRocket, faComments, faSitemap, faPerson, faGears, faBoxesStacked, faDesktop, faBasketShopping, faShieldHalved, faChartColumn, faExpand, faPlus, faArrowUpRightFromSquare, faSquarePhone, faPhoneFlip, faListOl, faWandMagicSparkles, faMaximize, faCaretRight, faSignsPost} from '@fortawesome/free-solid-svg-icons'
import { faFacebookF, faTwitter, faYoutube, faInstagram, faLinkedinIn, faTiktok, faBehance, faPinterestP} from '@fortawesome/free-brands-svg-icons'

import { faMinus} from '@fortawesome/free-solid-svg-icons'
import {faRoad, faVideo, faDroplet, faAngleRight} from '@fortawesome/free-solid-svg-icons'
import { faGoogle} from '@fortawesome/free-brands-svg-icons'
import { faWifi } from '@fortawesome/free-solid-svg-icons'
import { faAngleLeft } from '@fortawesome/free-solid-svg-icons'
import { faFlag } from '@fortawesome/free-solid-svg-icons'
import { faUser } from '@fortawesome/free-solid-svg-icons'
import { faSliders } from '@fortawesome/free-solid-svg-icons'
import { faLeaf } from '@fortawesome/free-solid-svg-icons'
import { faArrowsSpin } from '@fortawesome/free-solid-svg-icons'
import { faLayerGroup } from '@fortawesome/free-solid-svg-icons'
import { faUserTie } from '@fortawesome/free-solid-svg-icons'
import { faBriefcase } from '@fortawesome/free-solid-svg-icons'
import { faAnglesRight } from '@fortawesome/free-solid-svg-icons'
import { faPlay } from '@fortawesome/free-solid-svg-icons'
import { faCircleCheck } from '@fortawesome/free-solid-svg-icons'
import { faHandHoldingHand } from '@fortawesome/free-solid-svg-icons'
import { faCircleQuestion } from '@fortawesome/free-solid-svg-icons'
import { faBuildingLock } from '@fortawesome/free-solid-svg-icons'
import { faComputer } from '@fortawesome/free-solid-svg-icons'
import { faMagnifyingGlassChart } from '@fortawesome/free-solid-svg-icons'
import { faFileCircleCheck } from '@fortawesome/free-solid-svg-icons'
import { faAward } from '@fortawesome/free-solid-svg-icons'
import { faCubes } from '@fortawesome/free-solid-svg-icons'
import { faFolderOpen } from '@fortawesome/free-solid-svg-icons'
import { faShuttleSpace } from '@fortawesome/free-solid-svg-icons'
import { faPersonDotsFromLine } from '@fortawesome/free-solid-svg-icons'
import { faLaptopCode } from '@fortawesome/free-solid-svg-icons'
import { faPhoneVolume } from '@fortawesome/free-solid-svg-icons'
import { faLocationDot } from '@fortawesome/free-solid-svg-icons'
import { faMessage } from '@fortawesome/free-regular-svg-icons'
import { faCirclePlus } from '@fortawesome/free-solid-svg-icons'
import { faCircleMinus } from '@fortawesome/free-solid-svg-icons'
import { faCloud } from '@fortawesome/free-solid-svg-icons'
import { faChartArea } from '@fortawesome/free-solid-svg-icons'
import { faCodeBranch } from '@fortawesome/free-solid-svg-icons'
import { faFolderTree } from '@fortawesome/free-solid-svg-icons'
import { faArrowLeft } from '@fortawesome/free-solid-svg-icons'
import { faTag } from '@fortawesome/free-solid-svg-icons'
import { faEye } from '@fortawesome/free-solid-svg-icons'
import { faQuoteLeft } from '@fortawesome/free-solid-svg-icons'
import { faUpRightAndDownLeftFromCenter } from '@fortawesome/free-solid-svg-icons'
import CoolLightBox from 'vue-cool-lightbox'
import 'vue-cool-lightbox/dist/vue-cool-lightbox.min.css'


library.add(   faExpand,  faArrowUpRightFromSquare, faArrowUpRightDots, faPeopleGroup, faChartPie, faSquarePlus, faSquarePollVertical, faRectangleList, faTiktok,  faTrophy, faRocket,  faSitemap, faPerson,  faBoxesStacked, faDesktop, faBasketShopping, faShieldHalved,  faSquarePhone, faPhoneFlip, faBehance, faListOl, faWandMagicSparkles, faMaximize,  faSignsPost, faPinterestP, faRotate, faHouseChimney, faTruckMoving, faSuitcase, faUsers, faLightbulb, faGlobe, faEnvelope, faPhone, faPlus, faMinus, faRoad, faVideo, faDroplet, faGoogle, faGear, faBuilding, faChartColumn, faLink, faFacebookF, faTwitter, faLinkedinIn, faWifi, faYoutube, faMagnifyingGlass, faAngleDown, faAngleLeft, faFlag, faClock, faSliders, faAngleRight, faLeaf, faUser, faArrowsSpin, faLayerGroup, faUserTie, faGears, faComments, faBriefcase, faCaretRight, faAnglesRight, faPlay, faCircleCheck, faHandHoldingHand, faCircleQuestion, faBuildingLock, faComputer, faMagnifyingGlassChart, faFileCircleCheck, faAward, faCubes, faFolderOpen, faShuttleSpace, faPersonDotsFromLine, faLaptopCode, faPhoneVolume, faLocationDot, faMessage, faCirclePlus, faCircleMinus, faInstagram, faCloud, faChartArea, faCodeBranch, faFolderTree, faArrowLeft, faArrowRight, faUpRightAndDownLeftFromCenter, faTag, faEye, faQuoteLeft)

Vue.component('font-awesome-icon', FontAwesomeIcon)